export const assets = [
  { id: 'domain', name: 'example.com', type: 'Root domain', relation: 'Assessment scope', position: [50, 15], details: 'A 203.0.113.10 · MX mail.example.com', findings: [] },
  { id: 'app', name: 'app.example.com', type: 'Web application', relation: 'Subdomain of example.com', position: [22, 46], details: 'HTTPS · React · Nginx', findings: ['F-101', 'F-104'] },
  { id: 'api', name: 'api.example.com', type: 'API', relation: 'Subdomain of example.com', position: [75, 43], details: 'HTTPS · REST API', findings: ['F-102', 'F-105'] },
  { id: 'mail', name: 'mail.example.com', type: 'Mail service', relation: 'MX for example.com', position: [50, 77], details: 'MX · TLS', findings: ['F-103'] },
];
export const initialFindings = [
  { id: 'F-101', title: 'Missing Content-Security-Policy header', asset: 'app.example.com', category: 'Web security', severity: 'Medium', evidence: 'Content-Security-Policy was not observed in the sample HTTP response headers.', impact: 'Reduces browser-side protection against certain injected content.', remediation: 'Define and test a Content-Security-Policy appropriate for the application.', status: 'Open', source: 'HTTP headers', detected: '2026-09-18' },
  { id: 'F-102', title: 'Certificate expires soon', asset: 'api.example.com', category: 'TLS', severity: 'High', evidence: 'Example certificate expiry: 2026-10-04, as represented in the sample certificate data.', impact: 'An expired certificate can disrupt trusted HTTPS connections.', remediation: 'Renew the certificate and verify automated renewal and monitoring.', status: 'In progress', source: 'TLS certificate', detected: '2026-09-18' },
  { id: 'F-103', title: 'Mail service lacks MTA-STS policy', asset: 'mail.example.com', category: 'DNS / mail', severity: 'Low', evidence: 'No _mta-sts TXT record was included in the sample DNS dataset.', impact: 'Mail transport policy is not explicitly advertised.', remediation: 'Evaluate and publish an MTA-STS policy for the mail domain.', status: 'Open', source: 'DNS records', detected: '2026-09-18' },
  { id: 'F-104', title: 'Session cookie missing Secure attribute', asset: 'app.example.com', category: 'Web security', severity: 'High', evidence: 'The sample Set-Cookie header does not include the Secure attribute.', impact: 'The session cookie may be sent over an unencrypted connection.', remediation: 'Set the Secure attribute for session cookies and enforce HTTPS.', status: 'Open', source: 'HTTP cookies', detected: '2026-09-18' },
  { id: 'F-105', title: 'Server version exposed in response', asset: 'api.example.com', category: 'Web security', severity: 'Low', evidence: 'The sample Server header includes a software version.', impact: 'Exposes implementation details that may help an attacker choose a target.', remediation: 'Review server header disclosure and keep the service patched.', status: 'Resolved', source: 'HTTP headers', detected: '2026-09-18' },
];
export const stages = ['Scope review', 'DNS discovery', 'Web analysis', 'TLS analysis', 'Technology', 'Repository', 'Findings', 'Risk', 'Report'];
export const modules = ['DNS & subdomains', 'Web security', 'TLS certificates', 'Technology detection', 'Repository security'];
